<a href="https://colab.research.google.com/github/Altusya/Case-Study/blob/main/3)_random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/Altusya/Case-Study/main/merged_data.csv"
data = pd.read_csv(url)
print(data.shape)
data.head(1)

(45211, 20)


client_id  age         job  marital education  account_id in_default  \
0    1000583   43  management  married  tertiary       19298         no   

   balance housing loan   contact  campaign_id  day month  duration  campaign  \
0   -127.0      no   no  cellular        19298    6   aug       400         2   

   pdays  previous poutcome        y  
0     -1         0  unknown  unknown

In [18]:
known = data[data['y'] != "unknown"]
known.shape

(4521, 20)

In [36]:
from sklearn.preprocessing import OneHotEncoder

num_features = ["age", "balance", "duration"]
cat_features = ["job", "marital", "education", "in_default", "housing", "loan", "month", "campaign", "poutcome"]

X_num = known[num_features].values
ohe = OneHotEncoder(drop="first")
X_result = ohe.fit_transform(known[cat_features])
X_cat = X_result.toarray()
X_array = np.hstack((X_num, X_cat))
X_df = pd.DataFrame(columns=ohe.get_feature_names_out(cat_features))

y_array = known["y"].apply(lambda x: 1 if x == 'yes' else 0).values # To create a NumPy array from a pandas Series, you can use the .values attribute.


print(X_array.shape)
print(X_array)
print(y_array.shape)
print(y_array)

(4521, 67)
[[ 4.800e+01  5.543e+03  1.430e+02 ...  0.000e+00  0.000e+00  1.000e+00]
 [ 4.600e+01 -2.160e+02  4.040e+02 ...  0.000e+00  0.000e+00  1.000e+00]
 [ 3.600e+01  3.343e+03  3.070e+02 ...  0.000e+00  0.000e+00  1.000e+00]
 ...
 [ 3.300e+01  3.975e+03  5.150e+02 ...  1.000e+00  0.000e+00  0.000e+00]
 [ 4.300e+01  3.600e+01  1.180e+02 ...  0.000e+00  0.000e+00  0.000e+00]
 [ 4.900e+01  5.100e+01  9.840e+02 ...  0.000e+00  0.000e+00  1.000e+00]]
(4521,)
[0 0 0 ... 0 0 0]


In [37]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X_array, y_array, test_size=0.4, random_state=42)

trees = [50, 75, 100, 125, 150, 200, 250, 300]
leaves = [2, 3, 4, 5, 6, 7, 8, 9, 10]
criterions = ["gini", "entropy", "log_loss"]

for tree in trees:
  for leaf in leaves:
    for criterion in criterions:
      clf = RandomForestClassifier(n_estimators = tree, criterion=criterion, min_sample_leaf=leaf)
      clf.fit(X_train, y_train)
      y_pred = clf.predict(X_test)
      accuracy = accuracy_score(y_test, y_pred)
      print(f"{tree} / {leaf} / {criterion:<8}\t acc: {accuracy*100:.2f}%")

Accuracy: 89.72%
